logging:
  log-path: /Users/I753307/Downloads/logs

spring:
  datasource:
    password:

massive:
  base-url: http://localhost:9001/

# Python yfinance REST service
python:
  yfinance-url: http://localhost:9001/