logging:
  log-path: /Users/rama/Downloads/logs

spring:
  datasource:
    password: password

massive:
  base-url: https://api.massive.com/
  #base-url: http://localhost:9003/
  #base-url: http://localhost:9001/
