server:
  port: 8099

# Scheduler configuration for the cronjob profile
  # cron: "0 0/1 * * * *" # every 1 minutes

earnings:
  enabled: false
  cron: "0 0/1 * * * *" # every minute
  api:
    calls-per-minute: 1000

logging:
  cronjob:
    files:
      earnings: logs/earnings.log
      dayStockMovementData: logs/day-stock-movement-data.log
      dayStockMovementCleanup: logs/day-stock-movement-cleanup.log
      dayStockMovementKeyMapEntry: logs/day-stock-movement-key-map-entry.log
      weeklyUpcomingEarning: logs/weekly-upcoming-earnings.log
      dailyAnalystRating: logs/daily-analyst-rating.log
      optionSnapshotFetcher: logs/option-snapshot-fetcher.log


