server:
  port: 8099

# Scheduler configuration for the cronjob profile
  # cron: "0 0/1 * * * *" # every 1 minutes

earnings:
  enabled: false
  cron: "0 0/1 * * * *" # every minute
  api:
    calls-per-minute: 1000

# Populated the day stock movment data for the current day, after market close, Portugal time (Europe/Lisbon)
dayStockMovementData:
  enabled: true
  # cron: "0 0 22 * * MON-FRI" # after market close, 22:00 Portugal time (Europe/Lisbon)
  cron: "0 0/1 * * * *" # every 1 minutes

# Cleanup the day stock movement data for the current day, after market close, Portugal time (Europe/Lisbon)
dayStockMovementCleanup:
  enabled: false
   # default: every night at 8:00 after market close, Portugal time (Europe/Lisbon). Override via env as needed.
  cron: "0 0 8 * * MON-FRI" # after market close, 22:00 Portugal time (Europe/Lisbon)

# Populate the day stock movement key map entry for the current day, after market close, Portugal time (Europe/Lisbon)
dayStockMovementKeyMapEntry:
  enabled: false
  # default: every night at 21:00 after market close, Portugal time (Europe/Lisbon). Override via env as needed.
  cron: "0 0 21 * * MON-FRI" # after market close, 22:00 Portugal time (Europe/Lisbon)
  everyday-watchlist-codes: "MOVING_STOCK"

weeklyAnalystFirmUpdate:
  enabled: false
  cron: "0 0 21 * * SUN" # every Sunday at 21:00 Portugal time

dailyAnalystRatingUpdate:
  enabled: true
  cron: "0 0/1 * * * *" # every Sunday at 21:00 Portugal time
  watchlist-codes: "MOVING_STOCK"

#Populate the weekly upcoming earnings for the next week, after market close, Portugal time (Europe/Lisbon)
weeklyUpcomingEarning:
  enabled: false 
  cron: "0 0 21 * * FRI" # every Monday at 08:00 Portugal time
  # Comma-separated watchlist codes whose stocks are queried against the yfinance service
  watchlists: "MOVING_STOCK"

logging:
  cronjob:
    files:
      earnings: logs/earnings.log
      dayStockMovementData: logs/day-stock-movement-data.log
      dayStockMovementCleanup: logs/day-stock-movement-cleanup.log
      dayStockMovementKeyMapEntry: logs/day-stock-movement-key-map-entry.log
      weeklyUpcomingEarning: logs/weekly-upcoming-earnings.log


