spring:
  profiles:
    active: 
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mud?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8085
  error:
    include-stacktrace: ALWAYS

alphavantage:
  function: TIME_SERIES_DAILY
  apikey: ${ALPHA_VANTAGE_API_KEY:ISIX6TNS4RRINGGI}

massive:
  #base-url: https://api.massive.com/
  base-url: http://localhost:9003/
  open-close: v1/open-close/%s/%s/%s?adjusted=true&apiKey=%s
  ticker-aggregate: v2/aggs/ticker/%s/range/1/day/%s/%s?adjusted=true&apiKey=%s
  option-snapshot: v3/snapshot/options/%s?strike_price=%s&expiration_date=%s&apiKey=%s
  benzinga-firm: benzinga/v1/firms?limit=1000&sort=name.asc&apiKey=%s
  benzinga-firm-id: benzinga/v1/firms?benzinga_id=%s&limit=1000&sort=name.asc&apiKey=%s
  benzinga-analyst: benzinga/v1/analysts?benzinga_id=%s&apiKey=%s
  benzinga-analyst-rating: benzinga/v1/ratings?ticker=%s&last_updated.gte=%s&apiKey=%s
  apikey: ${MASSIVE_API_KEY:0jSwNlbvfYIgQ8OAVJsZ7T1sEmpWm7JV}

python:
# Python Service Local Instance url
  yfinance-url: http://localhost:8087/
  ticker: ticker/%s
master:
  tables:
    - master_market_holidays

all-cronjob-schedule: "0 0/1 * * * *"
